[[challenges]]
title = "Counting Down"
description = "Let's manage a loop!"
maxBytes = 35
maxTokens = 20
textOut = "9876543210"
hasImageOut = false


[[challenges]]
title = "Hello, World"
description = "The classic first program is harder here than in most languages. Print out 'Hello World!'"
maxBytes = -1
maxTokens = -1
textOut = "Hello, World!"
hasImageOut = false
imageOut = 0